//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegister.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpId { get; set; }
        [Required(ErrorMessage ="Please Enter Employee Tag")]
        public string EmpTag { get; set; }
        [Required(ErrorMessage = "Please Enter Firstname")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Please Enter Lastname")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [EmailAddress(ErrorMessage = "Please Enter Valid email")]
        public string Email { get; set; }
        public int DepartmentId { get; set; }
        [Required(ErrorMessage ="Please Enter Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        public int DesignationId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
